name: Playwright Tests

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Especifica la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test